### ISSUE TITLE
What's the difference of your implementation to nabu?

### ISSUE THREAD

**Issue by mjhanphd** [WindQAQ/listen-attend-and-spell#2]
You cited nabu as one of references.
Then, what's the difference of yours to nabu?
Have you performed any comparative case study?

**Comment by WindQAQ** [comment]
Nabu's implementation combines Kaldi's pipeline, which makes the whole procedure more robust. However, not all guys need such complicated steps (both in configuration and training). As for the tensorflow part, nabu's implementation does lots of self-implemented features, such as "LocationAwareAttention", manually stacking odd and even timestep for pLSTM using for loop and manual beam search decoder instead of using tensorflow.contrib.seq2seq.

In my implemention,  the dataset API is used, which can speed up the data reading part according to tensorflow official guide. Moreover, it depends on only *tensorflow* so users don't need to configure other requirements.

As for the performance, you can see [this analysis](https://imatge.upc.edu/web/sites/default/files/pub/x.pdf) to figure out it.

Thank you.
