### ISSUE TITLE
Additional mapping parameter.

### ISSUE THREAD

**Issue by ajinkyaT** [WindQAQ/listen-attend-and-spell#6]
Hi,

 May I know more about additional mapping parameter while evaluation? What does it mean? is it an optional parameter? Is it same as vocab table? link to code [here](https://github.com/WindQAQ/listen-attend-and-spell/blob/458cc2885d25e64ea43a9d30ff4da19f877f0392/utils/metrics_utils.py#L33)

**Comment by WindQAQ** [comment]
Hello,

This is exactly the optional parameter. While evaluation, some ASR task will need to *merge similar tokens*. Such as TIMIT, the evaluation uses 39 phone set instead of 48 one, see [TIMIT dataset](http://cdn.intechopen.com/pdfs/15948/InTech-Phoneme_recognition_on_the_timit_database.pdf) for more details.

Now talk about format of this mapping. It can be specified with `--mapping`. Consider you have the vocab table like
```
a
b
c
d
```
and you want to map `a -> c`, `b -> b`, `c -> c`, and `d -> d`.
then this mapping file should be
```
0
1
2
5
4
5
6
```
where the first three lines are reserved (UNK, SOS, and EOS). And the remaining lines represent *what id should each vocab be mapped to*. Let's take a look at the fourth line `5`. `5` is the id of `c`, which can be counted as the line number of `c` in vocab table +2. So this means that `a` should be mapped to `c`.

(Though I know this is definitely not the best way to achieve this goal.)
